# Site settings
title: "Pratik | Resume"
description: ""

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Pratik Choudhari"
resume_title:                   "About Me"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "choudh12@uwindsor.ca"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "Windsor, ON"

resume_header_contact_info:     "Windsor, ON â€¢ choudh12@uwindsor.ca"
display_header_contact_info:    "true"

resume_header_intro: "<p>Experienced data engineer with a passion for writing readable, maintainable and modular code. Expert in Python, SQL, Pandas, and API development. 
<br><br>ğŸŒŸThings I love:
<ul>
<li>ğŸµMusic - No seriously, can't live without it</li>
<li>ğŸPython - Being easy to learn can be both an advantage and a drawback. I took the advantage ğŸ˜</li>
<li>ğŸŒµCactii and succulents</li>
<li>ğŸ’»Data - Collection, manipulation and analysis. Well-versed in Pandas</li>
<li>ğŸ—£ï¸Productive conversions - Let's make them a norm</li>
<li>ğŸ’ªOpen source - Support OSS and contribute</li>
</ul>
<br>ğŸ‘Things I frown upon:
<ul>
<li>ğŸ“œUnreadable code</li>
</ul>
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_certification:   true
# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/pratik-choudhari"
  resume_linkedin_url:          "https://www.linkedin.com/in/pratik-choudhari/"
  resume_medium_url:            "https://medium.com/@pratik-choudhari"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
